//! The `env` observation block, against the request the TypeScript built (#982).
//!
//! # The oracle is a whole real request, per day
//!
//! `fixtures/fold-env-ts.json` holds, for each captured golden day, the fold
//! capture's `obs`/`tail`/`modeStats` inputs beside the twelve `env` fields
//! `dist/lean/fold-payload.js` produced from them. Generated by
//! `fixtures/fold-env-ts.mjs`; the coordinates are shifted, so the fixture is
//! committable while the corpus stays gitignored.
//!
//! # Why whole-field equality and not spot checks
//!
//! Every field here is a positional TUPLE — `[ts, lat, lon, speed]` and
//! friends. Lean reads them by index, so a swapped pair or a dropped element is
//! not a decode error: the fold reads a longitude as a speed and answers. The
//! only honest check is the entire array.

use backend::fold_payload::{encode_mode_stats, encode_obs_and_tail};
use serde_json::Value;

#[test]
fn every_day_encodes_its_observations_as_the_typescript_does() {
    let raw = include_str!("fixtures/fold-env-ts.json");
    let days: Vec<Value> = serde_json::from_str(raw).expect("fixture parses");
    assert!(days.len() >= 20, "fixture shrank to {} days", days.len());

    for day in &days {
        let name = day.get("day").and_then(Value::as_str).unwrap_or("?");
        let cap = day.get("cap").expect("capture inputs");
        let want = day.get("env").and_then(Value::as_object).expect("env");

        let got = encode_obs_and_tail(cap.get("obs").expect("obs"), cap.get("tail"));

        for (k, expected) in want {
            if k == "modeStats" {
                continue;
            }
            let actual = got.get(k).unwrap_or_else(|| panic!("{name}: missing {k}"));
            assert_eq!(actual, expected, "{name}: env.{k} differs");
        }

        assert_eq!(
            &encode_mode_stats(cap.get("modeStats")),
            want.get("modeStats").expect("modeStats"),
            "{name}: env.modeStats differs"
        );
    }
}

/// ⚠ `points` and `speedByTs` come from ONE source array and must stay
/// consistent, since the fold uses the second to look up the first.
#[test]
fn the_speed_lookup_matches_the_track_it_is_derived_from() {
    let raw = include_str!("fixtures/fold-env-ts.json");
    let days: Vec<Value> = serde_json::from_str(raw).expect("fixture parses");
    let day = days.first().expect("at least one day");
    let got = encode_obs_and_tail(
        day.get("cap").and_then(|c| c.get("obs")).expect("obs"),
        day.get("cap").and_then(|c| c.get("tail")),
    );

    let points = got["points"].as_array().expect("points");
    let speeds = got["speedByTs"].as_array().expect("speedByTs");
    assert_eq!(points.len(), speeds.len());
    for (p, s) in points.iter().zip(speeds) {
        assert_eq!(p[0], s[0], "timestamps must line up");
        assert_eq!(p[3], s[1], "the speed must be the same bit pattern");
    }
}
