//! The `env` observation block, against the request the TypeScript built (#982).
//!
//! # The oracle is a whole real request, per day
//!
//! `fixtures/fold-env-ts.json` holds, for each captured golden day, the fold
//! capture's `obs`/`tail`/`modeStats` inputs beside the twelve `env` fields
//! `dist/lean/fold-payload.js` produced from them. Generated by
//! `fixtures/fold-env-ts.mjs`; the coordinates are shifted, so the fixture is
//! committable while the corpus stays gitignored.
//!
//! # Why whole-field equality and not spot checks
//!
//! Every field here is a positional TUPLE — `[ts, lat, lon, speed]` and
//! friends. Lean reads them by index, so a swapped pair or a dropped element is
//! not a decode error: the fold reads a longitude as a speed and answers. The
//! only honest check is the entire array.

use backend::fold_payload::{
    encode_caches, encode_lookups, encode_mode_stats, encode_obs_and_tail, encode_places,
};
use serde_json::Value;

#[test]
fn every_day_encodes_its_observations_as_the_typescript_does() {
    let raw = include_str!("fixtures/fold-env-ts.json");
    let days: Vec<Value> = serde_json::from_str(raw).expect("fixture parses");
    assert!(days.len() >= 20, "fixture shrank to {} days", days.len());

    for day in &days {
        let name = day.get("day").and_then(Value::as_str).unwrap_or("?");
        let cap = day.get("cap").expect("capture inputs");
        let want = day.get("env").and_then(Value::as_object).expect("env");

        let got = encode_obs_and_tail(cap.get("obs").expect("obs"), cap.get("tail"));

        let places = encode_places(cap.get("knownPlaces"));
        let caches = encode_caches(
            cap.get("hsmmDecode"),
            cap.get("railRouteCache"),
            cap.get("busRouteCache"),
            cap.get("railStopsCache"),
        )
        .expect("the caches encode");

        for (k, expected) in want {
            if k == "modeStats" {
                continue;
            }
            if k == "lookups" {
                assert_eq!(
                    &encode_lookups(cap.get("trace"), cap.get("tzAt"), cap.get("bestPlace"))
                        .expect("lookups encode"),
                    expected,
                    "{name}: env.lookups differs"
                );
                continue;
            }
            if let Some(actual) = places.get(k).or_else(|| caches.get(k)) {
                assert_eq!(actual, expected, "{name}: env.{k} differs");
                continue;
            }
            let actual = got.get(k).unwrap_or_else(|| panic!("{name}: missing {k}"));
            assert_eq!(actual, expected, "{name}: env.{k} differs");
        }

        assert_eq!(
            &encode_mode_stats(cap.get("modeStats")),
            want.get("modeStats").expect("modeStats"),
            "{name}: env.modeStats differs"
        );
    }
}

/// ⚠ `points` and `speedByTs` come from ONE source array and must stay
/// consistent, since the fold uses the second to look up the first.
#[test]
fn the_speed_lookup_matches_the_track_it_is_derived_from() {
    let raw = include_str!("fixtures/fold-env-ts.json");
    let days: Vec<Value> = serde_json::from_str(raw).expect("fixture parses");
    let day = days.first().expect("at least one day");
    let got = encode_obs_and_tail(
        day.get("cap").and_then(|c| c.get("obs")).expect("obs"),
        day.get("cap").and_then(|c| c.get("tail")),
    );

    let points = got["points"].as_array().expect("points");
    let speeds = got["speedByTs"].as_array().expect("speedByTs");
    assert_eq!(points.len(), speeds.len());
    for (p, s) in points.iter().zip(speeds) {
        assert_eq!(p[0], s[0], "timestamps must line up");
        assert_eq!(p[3], s[1], "the speed must be the same bit pattern");
    }
}

/// ⚠ THE SAME FIELD, TWO DEFAULTS, AND THE CORPUS EXERCISES NEITHER.
///
/// `radiusM` is `optBits(p.radiusM)` in `stayPlaces` and `bits(p.radiusM ?? 50)`
/// in `enrichPlaces` — absent stays absent in one and becomes fifty metres in
/// the other. Both are the TypeScript's, on one field, three lines apart.
///
/// This is a hand-built case because ABLATION SHOWED THE CORPUS CANNOT SEE IT:
/// every captured place carries a radius, so changing the default from 50 to 0
/// left all 35 days passing. A comment asserting the default matters, with
/// nothing able to fail, is the shape this repository keeps getting bitten by.
#[test]
fn an_absent_radius_defaults_in_one_view_and_stays_absent_in_another() {
    let places = serde_json::json!([{
        "id": 1, "centroidLat": 51.5, "centroidLon": -0.1,
        "uniqueDays": 3, "sleepHours": 0.0, "hourProfile": null,
        "displayName": null, "amenityLabel": null
        // radiusM deliberately absent
    }]);
    let got = encode_places(Some(&places));

    let stay = &got["stayPlaces"][0];
    assert_eq!(
        stay[2],
        Value::Null,
        "stayPlaces keeps an absent radius absent"
    );

    let enrich = &got["enrichPlaces"][0];
    assert_eq!(
        enrich[3],
        Value::String(backend::fold_payload::bits(50.0)),
        "enrichPlaces substitutes fifty metres"
    );

    // And the same run must not have invented a profile.
    assert_eq!(
        enrich[5],
        Value::Null,
        "no hour profile is not a profile of zeroes"
    );
}

/// ⚠ A CORRUPT CACHE ROW IS AN ERROR, not an absent route.
///
/// `railRouteCache` carries its geometry as a JSON string inside the row. The
/// first version of the encoder dropped a row that would not parse and called
/// that an improvement on the TypeScript, which throws; `dev-lint`'s
/// `rust-serde-swallow` rejected it and was right. A dropped route is a matcher
/// scoring the day against a route set that is quietly missing something.
#[test]
fn an_unparseable_route_geometry_is_reported_not_skipped() {
    let bad = serde_json::json!([
        {"routeKey": "good", "geometryJson": "[{\"lat\":51.5,\"lon\":-0.1}]"},
        {"routeKey": "corrupt", "geometryJson": "{not json"}
    ]);
    let err = encode_caches(None, Some(&bad), None, None)
        .expect_err("a corrupt row must not be silently dropped");
    let msg = format!("{err:#}");
    assert!(msg.contains("corrupt"), "the error names the row: {msg}");

    // And the well-formed neighbour alone still encodes.
    let good =
        serde_json::json!([{"routeKey": "good", "geometryJson": "[{\"lat\":51.5,\"lon\":-0.1}]"}]);
    let ok = encode_caches(None, Some(&good), None, None).expect("a good row encodes");
    assert_eq!(ok["railRouteCache"].as_array().map(Vec::len), Some(1));
}
